metafood/urls.py
from django.conf.urls import url, include
from post import urls as post_urls
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('post.urls', namespace="question")),
]

post/urls.py
from django.conf.urls import url
from .views import (
	IndexView,
	PostDetailView,
    QuestionListView,
    CategoryView
)

app_name = 'post'

urlpatterns = [
    url(r'^$', IndexView.as_view()),
    url(r'^question/(?P<slug>[\w-]+)$', PostDetailView.as_view(), name="detail"),
    url(r'^category/(?P<slug>[\w-]+)$', CategoryView.as_view(), name="category_list"),    
    url(r'^api/questions/$', QuestionListView.as_view(), name="list"),
]

post/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

from taggit.managers import TaggableManager
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save


class Category(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField()

    def __unicode__(self):
        return self.title

class Question(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(editable=False)
    description = models.TextField()
    tags = TaggableManager()
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    author = models.ForeignKey(User)
    category = models.ManyToManyField(Category)

    def get_absolute_url(self):
        return reverse("question:detail", kwargs={"slug": self.slug})

    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ("-created",)

class Answer(models.Model):
    question = models.ForeignKey(Question)    
    description = models.TextField()
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return self.description

class Follow(models.Model):
    user = models.OneToOneField(User)
    category = models.ManyToManyField(Category)

    def __unicode__(self):
        return self.user.username + '  -  ' + "-".join(self.category.all().values_list('title', flat=True))

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    print "Created slug ", slug
    if new_slug is not None:
        slug = new_slug
        print "updated slug ", slug
    qs = Question.objects.filter(slug=slug).order_by("-id")
    print "qs ", qs
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        print "id", qs.first().id
        print "NEW SLUG", new_slug
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_reciever, sender=Question)

post/views.py
from django.http import HttpResponse
from django.shortcuts import render
from post.serializers import QuestionSerializer

from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView
from .models import  Question, Category
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status


class IndexView(ListView):
    model = Question
    template_name = "index.html"
    paginate_by = 5

    def get_queryset(self):
        # import pdb; pdb.set_trace()        
        return self.model.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        print "context", context
        categories = Category.objects.all()
        context['categories']=categories
        # import pdb; pdb.set_trace()    
        return context

class CategoryView(ListView):
    model = Question
    template_name = "category_index.html"
    
    def get_queryset(self):
        # import pdb; pdb.set_trace()
        slug = self.kwargs.get('slug')
        return Question.objects.filter(category__slug=slug)
    
    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        categories = Category.objects.all()
        context['categories']=categories
        # import pdb; pdb.set_trace()        
        return context


class PostDetailView(DetailView):
    model = Question
    template_name = "post_detail.html"
    # def get_context_data(self, **kwargs):
    #     context = super(PostDetailView, self).get_context_data(**kwargs)
    #     import pdb; pdb.set_trace()
    #     return context

class QuestionListView(APIView):
    def get(self, request, format=None):
        max_id = request.query_params.get('max_id')
        questions = Question.objects.filter(pk__lt=max_id)[:5]
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bare - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static "bootstrap/dist/css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    {% block categories %}
                    {%  endblock %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}
        {% endblock %}

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <script src='{% static "jquery/dist/jquery.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "bootstrap/dist/js/bootstrap.min.js" %}'></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#load").on("click", function() {
                var max_id = $(".post").last().data("pk");
                params = {'max_id':max_id};
                $.get("{% url 'question:list' %}", params, function(data) {
                    var posts = data;
                    var rendered_html = "";
                    $( posts ).each(function( index, post ) {
                        var html = $("<div />", {
                            "class" : "panel",
                            "text" : post.title
                        });
                        rendered_html = rendered_html + html.text();
                        console.log(html)
                    });
                    $("#load").html(rendered_html);
                });
            });
        });
    </script>

</body>

</html>

templates/category_index.html
{% extends "base.html" %}
{% block categories %}
{% for cat in categories %}
<li>
        <a href="{% url "question:category_list" cat.slug %}">{{ cat.title }}</a>
</li>
{% endfor %}                  
{% endblock %}
{% block content %}
<div class="row">
        {% for question in object_list %}
            <div class="post panel panel-default" data-pk={{ question.pk }}>
                <h3> <a href="{% url "question:detail" question.slug %}"> {{ question.title }} </a> </h3>
                <p> {{ question.description }} </p>
                <p> Asked by {{ question.author }} </p>
                {% for tag in question.tags.all %}
                        {{ tag }}
                {% endfor %}
           </div>
        {% endfor %}
        <div>
                <button class="btn btn-primary" id="load"> Load More </button>
        </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block categories %}
{% for cat in categories %}
<li>
        <a href="{% url "question:category_list" cat.slug %}">{{ cat.title }}</a>
</li>
{% endfor %}                  
{% endblock %}
{% block content %}
<div class="row">
        {% for question in object_list %}
            <div class="post panel panel-default" data-pk={{ question.pk }}>
                <h3> <a href="{% url "question:detail" question.slug %}"> {{ question.title }} </a> </h3>
                <p> {{ question.description }} </p>
                <p> Asked by {{ question.author }} </p>
                {% for tag in question.tags.all %}
                        {{ tag }}
                {% endfor %}
           </div>
        {% endfor %}
        <div>
                <button class="btn btn-primary" id="load"> Load More </button>
        </div>
</div>
{% endblock %}

templates/post_detail.html
{% extends "base.html" %}
{% block content %}
<h1> Question hun m {{ object }}</h1>
{% for ans in object.answer_set.all %}
<div class="row">
<h3> {{ ans }} </h3>
</br>
</div>
{% endfor %}
{% endblock %}

templates/question_list.html
{{ object_list }}